name       : compiz-plugins-extra
version    : 0.8.16
release    : 1
source     :
    - https://gitlab.com/compiz/compiz-plugins-extra/-/archive/v0.8.16/compiz-plugins-extra-v0.8.16.tar.bz2 : 318e8f14547b9f6a8143b7b79cd07b13ddd595b9df0fb59025d4c5c7a3e5da92
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Community extra Compiz compositing manager plugins.
description: |
    Community extra Compiz compositing manager plugins.
builddeps  :
    - pkgconfig(bcop)
    - pkgconfig(compiz)
    - pkgconfig(compiz-mousepoll)
    - pkgconfig(glu)
    - pkgconfig(libnotify)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
