name       : compiz-plugins-extra
version    : 0.8.18
release    : 2
source     :
    - https://gitlab.com/compiz/compiz-plugins-extra/-/archive/v0.8.18/compiz-plugins-extra-v0.8.18.tar.bz2 : 2b31cd8aaed9e22e9b7aee7a72f4c3f0e33c4dfb87404c1981311ce2d338d33f
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Community extra Compiz compositing manager plugins
description: |
    Community extra Compiz compositing manager plugins.
builddeps  :
    - pkgconfig(bcop)
    - pkgconfig(compiz-mousepoll)
    - pkgconfig(glu)
    - pkgconfig(libnotify)
rundeps    :
    - compiz-plugins-main
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
